apiVersion: v1
kind: Pod
metadata:
  name: annotations
  namespace: nginx-roboshop
  labels:
    project: roboshop
    environment: dev
    component: frontend
  annotations: 
    Imageregistry : "https://hub.docker.com"  
    jenkinsUrl: "https://jenkins.com/build/job/roboshop/32"

spec:
  containers:
    - name: nginx
      image: nginx