apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: nginx-roboshop

spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        # soft limit (minimum guaranteed resources)
        requests:
          memory: "64Mi"
          cpu: "100m"

        # hard limit (maximum allowed resources)
        limits:
          memory: "128Mi"
          cpu: "150m"