apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-1
spec:
  accessModes:
  - ReadWriteOnce # we can mount only once in node
  capacity:
    storage: 5Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c20f287ccbb4228e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-1
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static # This is  the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: ebs-static-1 