apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce # we can mount only once in node
  capacity:
    storage: 5Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08d732f0702b20950