apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs
spec:
  accessModes:
  - ReadWriteOnce # we can mount only once in node
  capacity:
    storage: 5Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-009c14f30e832d353
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs # This is  the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: ebs-static-1 