apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      # Hard Rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
            - us-east-1f
        containers:
         - name: nginx
           image: nginx      